# Рабочая тетрадь 1 Разшильдяев Александр

## 1.2.1 Пример
***Задача:***</br> Создать массив 5x2. Создать массив 5x2. Вывести все значения массива,
значение элемента с индексом (3,1) и второй столбец. Индексация
начинается с нуля.
</br> ***Решение:***

In [2]:
import numpy as np
x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


## 1.2.2 Пример
***Задача:***</br> Выполнить следующее:
1. Создать вектор (одномерный массив) размера 10, заполненный
нулями.
2. Создать вектор размера 10, заполненный единицами.
3. Создать вектор размера 10, заполненный заданным числом.
4. Создать вектор со значениями от 10 до 19.
</br> ***Решение:***

In [4]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, b, c, d, sep='\n')

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]
[10 11 12 13 14 15 16 17 18 19]


## 1.2.3 Пример
***Задача:***</br> Создать массив 10x10 со случайными значениями, найти минимум,
максимум и среднее значение.
</br> ***Решение:***

In [5]:
Z = np.random.random((10, 10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.002362469336740891 0.9910287394288765 0.5314795104412777


## 1.2.4 Пример
***Задача:***</br> Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице
местами.
</br> ***Решение:***

In [10]:
A = np.arange(25).reshape(5, 5)
A[[0, 1]]= A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


## 1.2.5 Пример
***Задача:***</br> Выяснить результат следующих выражений:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
</br> ***Решение:***

In [11]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


## 1.2.6 Пример
***Задача:***</br> Отсортировать массив
</br> ***Решение:***

In [12]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


## 1.3.1 Задание
***Задача:***</br> Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.
</br> ***Решение:***

In [18]:
mx = np.arange(64)
for x in range(64):
    mx[x] = (x / 8 + x % 8) % 2
mx = mx.reshape(8, 8)
print(mx)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 1.3.2 Задание
***Задача:***</br> Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange
</br> ***Решение:***

In [21]:
mx = np.arange(25)
for x in range(25):
    mx[x] = x % 5
mx = mx.reshape(5, 5)
print(mx)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


## 1.3.3 Задание
***Задача:***</br> Создать массив 3x3x3 со случайными значениями.
</br> ***Решение:***

In [30]:
cube = np.random.random((3, 3, 3))
print(cube)

[[[0.37885677 0.58094272 0.08112444]
  [0.17646491 0.51063355 0.3183359 ]
  [0.71747633 0.9604506  0.56718198]]

 [[0.75060281 0.24440191 0.17190726]
  [0.10809311 0.596912   0.31153533]
  [0.64293993 0.12310483 0.14668144]]

 [[0.60574884 0.96784292 0.47182298]
  [0.82529551 0.52173912 0.70706739]
  [0.35819732 0.74814822 0.04141651]]]


## 1.3.4 Задание
***Задача:***</br> Создать матрицу с 0 внутри, и 1 на границах.
</br> ***Решение:***

In [46]:
w = 6
h = 8
mx = np.arange(w*h)
for x in range(w*h):
    mx[x] = x % w % (w-1) == 0 or x // w % (h-1) == 0
mx = mx.reshape(h, w)
print(mx)

[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


## 1.3.5 Задание
***Задача:***</br> Создайте массив и отсортируйте его по убыванию.
</br> ***Решение:***

In [32]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr = np.sort(arr)[::-1]
print(arr)

[8 7 6 5 4 3 2 1]


## 1.3.6 Задание
***Задача:***</br> Создайте матрицу, выведите ее форму, размер и размерность.
</br> ***Решение:***

In [43]:
w = 6
h = 8
mx = np.arange(w*h).reshape(h, w)
print(f'size={np.size(mx)}')
print(f'shape={np.shape(mx)}')
print(f'size={np.dimm(mx)}')

size=48
shape=(8, 6)


AttributeError: module 'numpy' has no attribute 'dimm'