# Рабочая тетрадь 1 Разшильдяев Александр

## 1.2.1 Пример
***Задача:***</br> Создать массив 5x2. Создать массив 5x2. Вывести все значения массива,
значение элемента с индексом (3,1) и второй столбец. Индексация
начинается с нуля.
</br> ***Решение:***

In [2]:
import numpy as np
x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


## 1.2.2 Пример
***Задача:***</br> Выполнить следующее:
1. Создать вектор (одномерный массив) размера 10, заполненный
нулями.
2. Создать вектор размера 10, заполненный единицами.
3. Создать вектор размера 10, заполненный заданным числом.
4. Создать вектор со значениями от 10 до 19.
</br> ***Решение:***

In [4]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, b, c, d, sep='\n')

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]
[10 11 12 13 14 15 16 17 18 19]


## 1.2.3 Пример
***Задача:***</br> Создать массив 10x10 со случайными значениями, найти минимум,
максимум и среднее значение.
</br> ***Решение:***

In [5]:
Z = np.random.random((10, 10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.002362469336740891 0.9910287394288765 0.5314795104412777


## 1.2.4 Пример
***Задача:***</br> Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице
местами.
</br> ***Решение:***

In [10]:
A = np.arange(25).reshape(5, 5)
A[[0, 1]]= A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


## 1.2.5 Пример
***Задача:***</br> Выяснить результат следующих выражений:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
</br> ***Решение:***

In [11]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


## 1.2.6 Пример
***Задача:***</br> Отсортировать массив
</br> ***Решение:***

In [12]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


## 1.3.1 Задание
***Задача:***</br> Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.
</br> ***Решение:***

In [18]:
mx = np.arange(64)
for x in range(64):
    mx[x] = (x / 8 + x % 8) % 2
mx = mx.reshape(8, 8)
print(mx)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 1.3.2 Задание
***Задача:***</br> Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange
</br> ***Решение:***

In [21]:
mx = np.arange(25)
for x in range(25):
    mx[x] = x % 5
mx = mx.reshape(5, 5)
print(mx)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


## 1.3.3 Задание
***Задача:***</br> Создать массив 3x3x3 со случайными значениями.
</br> ***Решение:***

In [30]:
cube = np.random.random((3, 3, 3))
print(cube)

[[[0.37885677 0.58094272 0.08112444]
  [0.17646491 0.51063355 0.3183359 ]
  [0.71747633 0.9604506  0.56718198]]

 [[0.75060281 0.24440191 0.17190726]
  [0.10809311 0.596912   0.31153533]
  [0.64293993 0.12310483 0.14668144]]

 [[0.60574884 0.96784292 0.47182298]
  [0.82529551 0.52173912 0.70706739]
  [0.35819732 0.74814822 0.04141651]]]


## 1.3.4 Задание
***Задача:***</br> Создать матрицу с 0 внутри, и 1 на границах.
</br> ***Решение:***

In [46]:
w = 6
h = 8
mx = np.arange(w*h)
for x in range(w*h):
    mx[x] = x % w % (w-1) == 0 or x // w % (h-1) == 0
mx = mx.reshape(h, w)
print(mx)

[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


## 1.3.5 Задание
***Задача:***</br> Создайте массив и отсортируйте его по убыванию.
</br> ***Решение:***

In [32]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr = np.sort(arr)[::-1]
print(arr)

[8 7 6 5 4 3 2 1]


## 1.3.6 Задание
***Задача:***</br> Создайте матрицу, выведите ее форму, размер и размерность.
</br> ***Решение:***

In [3]:
w = 6
h = 8
mx = np.arange(w*h).reshape(h, w)
print(f'size={np.size(mx)}')
print(f'shape={np.shape(mx)}')
print(f'size={np.ndim(mx)}')

size=48
shape=(8, 6)
size=2


## 2.2.1 Пример
***Задача:***</br> Создать Series из списка Python, словаря Python, и массива Numpy
(установить буквенные метки для последнего).
</br> ***Решение:***

In [4]:
import pandas as pd
import numpy as np
lst = [1, 2, 3, 4, 5]
d = {'a':1, 'b':2, 'c':3}
ndarr = np.array([1, 2, 3, 4, 5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])
print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int32


## 2.2.2 Пример
***Задача:***</br> Дано два Series. Напечатать их первые элементы и все элементы после
третьего (во втором фрейме).
</br> ***Решение:***

In [5]:
s1 = pd.Series([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([5, 4, 3, 2, 1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


## 2.2.3 Пример
***Задача:***</br> Создайте новый фрейм данных.
</br> ***Решение:***

In [5]:
import pandas as pd
import numpy as np
dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
dataframe['Возраст'] = [38, 25]
dataframe['Водитель'] = [True, False]
dataframe

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

## 2.2.4 Пример
***Задача:***</br> Загрузите фрейм данных по ссылке:
https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv
</br> ***Решение:***

In [6]:
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataframe = pd.read_csv(url)
dataframe.head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

## 2.2.5 Пример
***Задача:***</br> Пронализировать характеристики фрейма данных
</br> ***Решение:***

In [17]:
from IPython.display import display

display(dataframe.head(2))
display(dataframe.tail(3))
display(dataframe.shape)
display(dataframe.describe())


Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

Name PClass   Age   Sex  Survived  SexCode
1310  Zenni, Mr Philip    3rd  22.0  male         0        0
1311  Lievens, Mr Rene    3rd  24.0  male         0        0
1312    Zimmerman, Leo    3rd  29.0  male         0        0

(1313, 6)

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

## 2.2.6 Пример
***Задача:***</br> Выберите индивидуальные данные или срезы фрейма данных.
</br> ***Решение:***

In [24]:
dataframe.iloc[25:100:25]

Name PClass   Age   Sex  Survived  SexCode
25  Blackwell, Mr Stephen Weart    1st  45.0  male         0        0
50  Carter, Master William T II    1st  11.0  male         1        0
75     Cumings, Mr John Bradley    1st  39.0  male         0        0

## 2.2.7 Пример
***Задача:***</br> Требуется отобрать строки фрейма данных на основе некоторого условия. Необходимо сформировать новый фрейм данных из пассажиров
первого класса.
</br> ***Решение:***

In [25]:
dataframe[dataframe['PClass'] == '1st'].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

## 2.3.1 Задача
***Задача:***</br> Найдитн евклидово расстояние между двумя Series (точками) a и b, не используя встроенную формулу.
</br> ***Решение:***

In [26]:
def e_distance(a, b):
    return np.sqrt(np.sum((a - b) ** 2))


a = pd.Series([12, 7, 6])
b = pd.Series([2, 4, 3])
print(e_distance(a, b))

10.862780491200215


## 2.3.2 Задача
***Задача:***</br> Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данных можно найти
здесь: https://github.com/akmand/datasets)
</br> ***Решение:***

In [32]:
url = 'https://raw.githubusercontent.com/akmand/datasets/main/melbourne_house_prices.csv'
dataframe = pd.read_csv(url)
dataframe.head(5)

Date        Suburb  Rooms Type Method    SellerG  Distance  Postcode  \
0  23/09/2017    Aberfeldie      5    h      S    Rendina       7.5      3040   
1  23/09/2017  Airport West      3    h      S       Brad      10.4      3042   
2  23/09/2017  Airport West      3    h      S  Harcourts      10.4      3042   
3  23/09/2017     Albanvale      3    h      S      Bells      14.0      3021   
4  23/09/2017   Albert Park      3    h     VB     Cayzer       3.0      3206   

   Bedroom2  Bathroom  Car  Landsize  BuildingArea  YearBuilt CouncilArea  \
0         5         4  4.0       730         373.0     2014.0         NaN   
1         3         1  2.0       551          96.0     1950.0         NaN   
2         3         2  2.0       593           NaN        NaN         NaN   
3         3         1  2.0       619           NaN        NaN         NaN   
4         3         2  NaN       137         125.0     1890.0         NaN   

   Lattitude  Longtitude             Regionname  Propertycount    Price  
0  -37.75950   144.89427   Western Metropolitan           1543  1830000  
1  -37.72739   144.88235   Western Metropolitan           3464   850000  
2  -37.72057   144.87558   Western Metropolitan           3464   860000  
3  -37.74521   144.76863   Western Metropolitan           1899   565000  
4  -37.84388   144.95303  Southern Metropolitan           3280  2100000

## 2.3.3 Задача
***Задача:***</br> Проделайте с получившемся из предыдущего задания фреймом данных
те же действия, что и в примерах 2.2.5-2.2.7.
</br> ***Решение:***

In [35]:
from IPython.display import display

display(dataframe.head(2))
display(dataframe.tail(3))
display(dataframe.shape)
display(dataframe.describe())
display(dataframe.iloc[25:100:25])
display(dataframe[dataframe['Rooms'] == 4].head(2))

Date        Suburb  Rooms Type Method  SellerG  Distance  Postcode  \
0  23/09/2017    Aberfeldie      5    h      S  Rendina       7.5      3040   
1  23/09/2017  Airport West      3    h      S     Brad      10.4      3042   

   Bedroom2  Bathroom  Car  Landsize  BuildingArea  YearBuilt CouncilArea  \
0         5         4  4.0       730         373.0     2014.0         NaN   
1         3         1  2.0       551          96.0     1950.0         NaN   

   Lattitude  Longtitude            Regionname  Propertycount    Price  
0  -37.75950   144.89427  Western Metropolitan           1543  1830000  
1  -37.72739   144.88235  Western Metropolitan           3464   850000

Date        Suburb  Rooms Type Method        SellerG  Distance  \
13577   4/02/2016    Yarraville      2    h      S  hockingstuart       7.0   
13578  28/01/2016  Surrey Hills      2    u      S      Fletchers      11.2   
13579  28/01/2016  Surrey Hills      3    h      S      Fletchers      11.2   

       Postcode  Bedroom2  Bathroom  Car  Landsize  BuildingArea  YearBuilt  \
13577      3013         2         1  0.0       166           NaN     1920.0   
13578      3127         2         1  2.0       108           NaN        NaN   
13579      3127         3         1  2.0       490           NaN        NaN   

       CouncilArea  Lattitude  Longtitude             Regionname  \
13577  Maribyrnong   -37.8209    144.8913   Western Metropolitan   
13578   Whitehorse   -37.8276    145.1023  Southern Metropolitan   
13579   Whitehorse   -37.8361    145.1006  Southern Metropolitan   

       Propertycount    Price  
13577           6543   890000  
13578           5457   813000  
13579           5457  1205000

(13580, 20)

Rooms      Distance      Postcode      Bedroom2      Bathroom  \
count  13580.000000  13580.000000  13580.000000  13580.000000  13580.000000   
mean       2.937997     10.137776   3105.301915      2.914728      1.534242   
std        0.955748      5.868725     90.676964      0.965921      0.691712   
min        1.000000      0.000000   3000.000000      0.000000      0.000000   
25%        2.000000      6.100000   3044.000000      2.000000      1.000000   
50%        3.000000      9.200000   3084.000000      3.000000      1.000000   
75%        3.000000     13.000000   3148.000000      3.000000      2.000000   
max       10.000000     48.100000   3977.000000     20.000000      8.000000   

                Car       Landsize  BuildingArea    YearBuilt     Lattitude  \
count  13518.000000   13580.000000   7130.000000  8205.000000  13580.000000   
mean       1.610075     558.416127    151.967650  1964.684217    -37.809203   
std        0.962634    3990.669241    541.014538    37.273762      0.079260   
min        0.000000       0.000000      0.000000  1196.000000    -38.182550   
25%        1.000000     177.000000     93.000000  1940.000000    -37.856822   
50%        2.000000     440.000000    126.000000  1970.000000    -37.802355   
75%        2.000000     651.000000    174.000000  1999.000000    -37.756400   
max       10.000000  433014.000000  44515.000000  2018.000000    -37.408530   

         Longtitude  Propertycount         Price  
count  13580.000000   13580.000000  1.358000e+04  
mean     144.995216    7454.417378  1.075684e+06  
std        0.103916    4378.581772  6.393107e+05  
min      144.431810     249.000000  8.500000e+04  
25%      144.929600    4380.000000  6.500000e+05  
50%      145.000100    6555.000000  9.030000e+05  
75%      145.058305   10331.000000  1.330000e+06  
max      145.526350   21650.000000  9.000000e+06

Date          Suburb  Rooms Type Method SellerG  Distance  Postcode  \
25  23/09/2017      Black Rock      3    u      S     Ray      17.3      3193   
50  23/09/2017      Camberwell      4    h      S  Jellis       7.7      3124   
75  23/09/2017  Doncaster East      5    h      S     ASL      14.3      3109   

    Bedroom2  Bathroom  Car  Landsize  BuildingArea  YearBuilt CouncilArea  \
25         3         2  2.0       749           NaN     1980.0         NaN   
50         4         2  8.0       905           NaN        NaN         NaN   
75         5         2  2.0       659           NaN     1975.0         NaN   

    Lattitude  Longtitude             Regionname  Propertycount    Price  
25  -37.97676   145.01851  Southern Metropolitan           2866   945000  
50  -37.84578   145.08436  Southern Metropolitan           8920  2850000  
75  -37.78628   145.16670   Eastern Metropolitan          10999  1890000

Date          Suburb  Rooms Type Method  SellerG  Distance  Postcode  \
6  23/09/2017  Altona Meadows      4    h      S      YPA      15.5      3028   
8  23/09/2017    Altona North      4    h      S  Sweeney       9.4      3025   

   Bedroom2  Bathroom  Car  Landsize  BuildingArea  YearBuilt CouncilArea  \
6         4         2  2.0       636         232.0     1996.0         NaN   
8         4         1  5.0       561           NaN        NaN         NaN   

   Lattitude  Longtitude            Regionname  Propertycount   Price  
6  -37.87941   144.76935  Western Metropolitan           7630  750000  
8  -37.83224   144.85300  Western Metropolitan           5132  970000

## 3.2.1 Пример
***Задача:***</br> Прошкалируйте числовой признак в диапазон между двумя значениями.
</br> ***Решение:***

In [38]:
import numpy as np
from sklearn import preprocessing
feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
minmax_scale = preprocessing.MinMaxScaler(feature_range = (0, 1))
scaled_feature = minmax_scale.fit_transform(feature)
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

## 3.2.2 Пример
***Задача:***</br> Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное
отклонение 1
</br> ***Решение:***

In [41]:
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
scaler = preprocessing.StandardScaler()
standardized = scaler.fit_transform(x)
display(standardized)
print('Среднее:', round(standardized.mean()))
print('Стандартное отклонение:', standardized.std())

array([[-0.76058269],
       [-0.54177196],
       [-0.35009716],
       [-0.32271504],
       [ 1.97516685]])

Среднее: 0
Стандартное отклонение: 1.0


## 3.2.3 Пример
***Задача:***</br> Дан фрейм данных
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
'B':[103.02,107.26,110.35,114.23,114.68],
'C':['big','small','big','small','small']})
Необходимо масштабировать его числовые столбцы
</br> ***Решение:***

In [42]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21], 
                       'B':[103.02,107.26,110.35,114.23,114.68], 
                       'C':['big','small','big','small','small']})
dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A', 'B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

## 3.3.2 Задача
***Задача:***</br> Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.
</br> ***Решение:***

In [51]:
url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
dataframe = pd.read_csv(url)
minmaxscaler = preprocessing.MinMaxScaler(feature_range = (0, 1))
dataframe[['sepal_length_cm']] = minmaxscaler.fit_transform(dataframe[['sepal_length_cm']])
zscaler = preprocessing.StandardScaler()
dataframe[['sepal_width_cm']] = zscaler.fit_transform(dataframe[['sepal_width_cm']])
dataframe.head(5)

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0         0.222222        1.032057              1.4             0.2  setosa
1         0.166667       -0.124958              1.4             0.2  setosa
2         0.111111        0.337848              1.3             0.2  setosa
3         0.083333        0.106445              1.5             0.2  setosa
4         0.194444        1.263460              1.4             0.2  setosa